---
# tasks file for kibana
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    owner: 1000
    group: docker
    mode: '0755'
  loop:
    - { path: "{{ ansible_workdir }}/kibana" }

- name: Build and Copy docker-compose yaml to target
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ ansible_workdir }}/kibana/docker-compose.yml"
    mode: '0644'

- name: Run `docker-compose up`
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_workdir }}/kibana/"
    files:
      - docker-compose.yml
  register: compose

- name: Output of compose Kibana service
  ansible.builtin.debug:
    var: compose