---
- hosts: nginx
  become: true
  remote_user: user
  tasks:
    - name: "Install nginx"
      apt:
        name: "nginx"
        state: "latest"
        update_cache: true
    - service:
        name: "nginx"
        state: started
      become: true
      become_method: sudo