webserver_node_1: nginx-onex-webserver-host
webserver_node_2: nginx-yleg-webserver-host
kibana_password: TeSt123!
ansible_workdir: /home/anikulin/fops-sysadm-diplom/ansible_configs
telegram_bot_token: 
telegram_chat_id: ""
pg_cluster_id: c9qaml4ahhqhijed211p
pg_admin_password: Pg3TestPas1
