version: '3'
services:
  kibana:
    image: kibana:8.7.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana-coursework-anikulin
      # TODO: Add from terraforms
      ELASTICSEARCH_HOSTS: '["http://172.16.18.20:9200"]'
    ports:
      - "5601:5601"
    networks:
      - kibana

networks:
  kibana:
    driver: bridge