- name: Make home dir
  ansible.builtin.file:
    path: /var/www/site
    state: directory
    owner: ansible
    group: root
    mode: '0755'

- name: Copy assets
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  loop:
    - { src: assets, dest: /var/www/site/assets}
    - { src: images, dest: /var/www/site/images}
    - { src: elements.html, dest: /var/www/site/elements.html}
    - { src: generic.html, dest: /var/www/site/generic.html}

- name: Copy server config
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  loop:
    - { src: server.conf, dest: /etc/nginx/sites-available/default}

- name: add html template
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  loop:
    - { src: index.html.j2, dest: /var/www/site/index.html}

- name: restart service NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted