- name: Test connection to hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: PING - Test connection
      ansible.builtin.ping:

- name: Setup html template on webservers
  hosts:
    - webservers
  roles:
    - site

- name: Setup docker engine and python plugins for docker compose
  hosts:
    - observability
  roles:
    - docker-host

- name: Elasticsearch setup
  hosts: elastic-host
  roles:
    - elasticsearch
  vars_files:
    - ./vars/terraform_vars.yml

- name: Kibana setup
  hosts: kibana-host
  roles:
    - kibana
  vars_files:
    - ./vars/terraform_vars.yml

- name: Configure Nginx Log Exporter on webservers
  hosts: webservers
  roles:
    - nginx-log-exporter
  vars_files:
    - ./vars/terraform_vars.yml

- name: Configure Node Exporter on each server
  hosts:
    - webservers
    - observability
  serial: 7
  roles:
    - node-exporter
  vars_files:
    - ./vars/terraform_vars.yml

- name: Prometheus setup
  hosts: prometheus-host
  roles:
    - pg-prom-adapter
    - alertmanager
    - prometheus
  vars_files:
    - ./vars/terraform_vars.yml

- name: Grafana setup
  hosts: grafana-host
  roles:
    - grafana
  vars_files:
    - ./vars/terraform_vars.yml

- name: Configure filebeats for nginx
  hosts:
    - webservers
  roles:
    - filebeat
  vars:
    mode: nginx
  vars_files:
    - ./vars/terraform_vars.yml

- name: Configure filebeats for containers
  hosts:
    - observability
  roles:
    - filebeat
  vars:
    mode: docker
  vars_files:
    - ./vars/terraform_vars.yml