---
# tasks file for elasticsearch
- name: set max virtual memory areas for Elasticsearch
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present

- name: Create workdir
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    owner: user
    group: docker
    mode: '0755'
  loop:
    - { path: "{{ ansible_workdir }}/elastic-conf" }
    - { path: "{{ ansible_workdir }}/elastic/data-01" }
    - { path: "{{ ansible_workdir }}/elastic/data-02" }
    - { path: "{{ ansible_workdir }}/elastic/data-03" }

- name: ELASTICSEARCH - Copy docker-compose yaml to target
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ ansible_workdir }}/elastic-conf/docker-compose.yml"
    mode: '0644'

- name: ELASTICSEARCH - Run `docker-compose up`
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_workdir }}/elastic-conf/"
    files: 
      - docker-compose.yml
  register: compose

- name: ELASTICSEARCH - Output of docker compose
  ansible.builtin.debug:
    var: compose